import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import CreatePost from "../src/components/CreatePost";
import { Post } from "../src/redux/slices/postsReducer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const posts = useSelector((state) => state.posts);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-col items-center justify-center ">
        <div>
          {posts.map((post: Post) => (
            <div key={post.id}>
              <h2 className="text-xl text-primary">{post.title}</h2>
              <p>{post.body}</p>
            </div>
          ))}
        </div>

        <CreatePost />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
