import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSelector, useDispatch } from "react-redux";
import { createPost, Post } from "../src/redux/slices/postsReducer";

const Home: NextPage = () => {
  const posts = useSelector((state) => state.posts);
  const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          {posts.map((post: Post) => (
            <div key={post.id}>
              <h2 className="text-xl text-primary">{post.title}</h2>
              <p>{post.body}</p>
            </div>
          ))}
        </div>

        <form id="main-login">
          <h2>Admin UI Login</h2>
          <label>
            <span>title:</span>
            <input type="email" name="email" />
            <br />
          </label>
          <br />
          <label>
            <span>password:</span>
            <input type="password" name="password" />
            <br />
          </label>
          <br />
          <div>
            <button
              onClick={() =>
                dispatch(
                  createPost({
                    id: "new id",
                    title: "new title",
                    body: "new body",
                  })
                )
              }
            >
              {" "}
              create post{" "}
            </button>
          </div>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
